### ISSUE TITLE
Data source priority - Glance

### ISSUE THREAD

**Issue by sequelae75** [tommasoberlose/another-widget#123]
Could be nice if it was possible to have both "Daily steps" and "Next clock alarm" or the possibility to for example set a timer on when the different providers could appear on the screen. For example I want my "daily steps" to show from 7 AM until 10 PM and let the "next clock alarm" to appear right before my bedtime. Feature request: let me decide when different provider should appear on my widget screen or the possibility to have 2 providers at the same time.

Thanks again for at good app.

**Comment by tommasoberlose** [comment]
Hey, the glance info are kinda difficult to handle.
The daily steps show up only after you have finished an activity like walking or running and they stay shown just for five minutes. That's because I can't update the steps counter with real-time data but just react to an activity start/stop event.
Also, the next alarm shows up only if set in the next 12 hours, so I think that you could change the priority of the providers to show the daily step with a higher priority of the next alarm and you will see both info without any problems.

It's also very difficult to show two provider info in one line because that could break the widget based on different languages.
