### ISSUE TITLE
I identified why next alarm was wrong.

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#158]
**Description**
It is because the widget uses different providers to Show next alarm.
Sometimes it is set by Horloge (Clock), sometimes it is set by Archive du calendrier (Calendar archive) [see error messages in screenshots].
But in the 1st place... why would an alarm can be set by Calendar archive??

**Expected behavior**
Always set the alarm app provider on Clock.

**Alternatives you've considered**
Now that i think about it, maybe you can show alarm/reminder from other apps that we **must choose** ''Alarm/reminder providers'' (Calendar, Reminders, Notes, Google Keep, etc).

Then all Glance that are alarm-related would be in a new category 'Alarm and reminders' and would not be part of 'Providers' category any longer.

If an alarm is displayed in the widget, then the icon (that is before the alarm time) is the current clock.
If a reminder (from Calendar, Keep, Notes, etc) is displayed in the widget, then the icon is a bell.

**Screenshots**
![Screenshot_2020-05-23-10-22-31-141_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/82725986-4ce6f300-9ce1-11ea-8ada-3912288724d8.jpg)
![Screenshot_2020-05-23-09-55-59-665_com tommasoberlose anotherwidget](https://user-images.githubusercontent.com/64771681/82725988-4d7f8980-9ce1-11ea-99af-fac6ce27e7ea.jpg)

**Smartphone:**
 - Device: Redmi Xiaomi Note 7
 - OS Version: Android 9 with MIUI 11
 - App Version: 2.0.12 (102)

**Comment by LastInLine** [comment]
This leads me to ask how far ahead does the widget display the next alarm?  I have a recurring alarm so there's always a next alarm set but it doesn't always display it so I assume there's some threshold beyond which it doesn't display.  The thing is, I've had it as close as ten hours and not display it which seems a bit odd given most people should sleep eight hours.

**Comment by tommasoberlose** [comment]
Unfortunately this issue is not related to Another Widget and I can't fix it.
Android handles the alarms in two different ways:
- applications can create internal alarms to get notified at a specific time and do some work. For example I use this system to update the time left to the event.
- otherwise applications can use `setAlarm` from the `AlarmManager` to create clock alarms. 

Unfortunately with the latest Android versions the first method is not reliable anymore so a lot of applications are using the second method to get notified at an exact moment, but this creates misbehavior with the API that returns the next alarm clock.
As you can see [here](https://github.com/tommasoberlose/another-widget/blob/e82a34bcc7803822c6d3426663dba7823c1f4d17/app/src/main/java/com/tommasoberlose/anotherwidget/helpers/AlarmHelper.kt#L11) I can just request the next alarm set in the entire system by every app and show in the widget. You can also refer to the [Android Docs](https://developer.android.com/reference/android/app/AlarmManager.html#getNextAlarmClock()).

So, I can't handle multiple "alarm providers" and an "alarm tolerance time" will not fix the issue, because this isn't related to Another Widget but to every application that set an Alarm with the wrong method. You can easily check that this behavior will also break the DnD feature "turn on until <next alarm>".
I added the possibility in the app to check the application that has set the wrong next alarm long-clicking on the Next Clock Alarm setting. Actually the only feasible solution is to have the right alarm in the widget you have to uninstall that app.

**Comment by tommasoberlose** [comment]
> This leads me to ask how far ahead does the widget display the next alarm? I have a recurring alarm so there's always a next alarm set but it doesn't always display it so I assume there's some threshold beyond which it doesn't display. The thing is, I've had it as close as ten hours and not display it which seems a bit odd given most people should sleep eight hours.

I've just fixed this issue.

**Comment by Moutony** [comment]
> I added the possibility in the app to check the application that has set the wrong next alarm long-clicking on the Next Clock Alarm setting. Actually the only feasible solution is to have the right alarm in the widget you have to uninstall that app.

It is impossible to uninstall ''Calendar archive'' because this app doesn't appear in the apps list in the Settings.

**Comment by tommasoberlose** [comment]
Unfortunately, I can't do anything about it. It seems that is the OS, or some related app, that set the wrong alarms but I can't access the full alarms list.

**Comment by p1x44r** [comment]
To fix this I have to periodically clear cache of "Calendar storage" system app (package name: com.android.providers.calendar).
