### ISSUE TITLE
Feature request: Change multiple event switcher from left/right arrows to vertical swipe (accessibility issue) 

### ISSUE THREAD

**Issue by e-t-l** [tommasoberlose/another-widget#179]
Even with the widget as large as possible, it's difficult to consistently tap the left/right arrows to switch events. I often end up tapping the event itself and launching my calendar. I'm neither old nor lacking in fine motor control, so I can only imagine how much more difficult this would be for some people.

As an alternative to improve accessibility, I suggest an option to switch between events by swiping up/down on the widget.

**Comment by tommasoberlose** [comment]
Hi @e-t-l , interaction with widgets is very limited.

The thing is, widgets aren't "mini applications," they are... widgets. They live in the world of, and are dependent upon, the real application containing them.

There is a continual demand for widgets to support more and more complicated interactions, but every time we start down that path it ends up making the interaction with the containing application much more complicated as well, and seems likely to negatively impact overall usability.

For example, if widgets can process swipes, then the user is now very uncertain about how they can swipe between screens because they will get different behavior depending where they swipe. They could even get stuck in a state where it is nearly impossible to swipe between screens because of the widgets covering the touchable area.

**Comment by e-t-l** [comment]
@tommasoberlose See, the neat thing about the issue I raised is, I actually specified a VERTICAL swipe. As in swiping up or down. As in the way hundreds of widgets currently process swipes, including every single calendar, list, and messages widget. As in the direction you can swipe on a screen that has absolutely no bearing to page navigation.

If you feel like putting in accessibility options (and I did specify this as an OPTION) aren't worth your time right now, that's fine and you can just say that. The least you could do is actually READ the issue before closing it, though.

**Comment by tommasoberlose** [comment]
@e-t-l I used the horizontal swipe just as an example, because every launcher use at the same time both directions to trigger some action (i.e. the swipe up/down open the notifications center on most of the Android devices).
Please believe me when I tell you that I'd already thought about a swipe gesture on the widget to hide those "not so good" arrows on both sides, but I wasn't able to figure out a way to do it.

The app widgets are actually based on very old APIs developed by the Android team and they barely support most of the design patterns that you could find in the mobile developing. The widgets that support the vertical swipe are based on a list structure that enables and handles the vertical scroll to show more than one information at a time.
I'm actually not able to handle any event that is different from the "tap" event on the widget.

I already did a lot of research on this feature and I closed the issue only because I was already sure that it couldn't be achieved.
