### ISSUE TITLE
Scrolling animation for the currently playing. Sometimes the track and artist name is too long and it would be nice if it scrolled. 

### ISSUE THREAD

**Issue by Josu25** [tommasoberlose/another-widget#184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tommasoberlose** [comment]
Hi @Josu25 ,
Android is making really difficult to develop a home widget right now, the APIs are really strict and even a simple animation like that could be very hard to achieve and very heavy for the device (it will cause battery drain due to the continuous redraw of the widget).

I'll work on this as soon as Google will update the home widget draw system.
