### ISSUE TITLE
What are "Relevent events"?

### ISSUE THREAD

**Issue by Moutony** [tommasoberlose/another-widget#199]
**Is your feature request related to a problem? Please describe.**
Yes, I don't know what you mean by those terms.

**Describe the solution you'd like**
- I don't understand what "Relevent events" are. Plus, the suitcase icon makes it even more confusing.
- Why? Because I see no option named like this in "Google Calendar" app.
- So I was wondering: Are they events that have a notification on? Or maybe events that have a "Google Meets" linked on?

**Describe alternatives you've considered**
- Make the description more precise. 
- Change the icon (example: if "Relevent events"=="Events with a notification on", then change the suitcase icon by a ring-bell).
- If nobody uses this option, or if it changes nothing compared to when it's toggled off, then remove it.

**Comment by tommasoberlose** [comment]
Hey @Moutony , you can refer to the issue #169 
That option is related to business accounts (that's why the suitcase) that have the option in an event to set that time spot as "busy". When you are "busy" you cannot be planned with other events in the same period.

I understand that the label is quite difficult to get even for those who have that option available, but I wasn't able to find a better one. I'll try to hide the option for those who haven't a G suite account.
