### ISSUE TITLE
Need 1 min event refresh frequency

### ISSUE THREAD

**Issue by devindang** [tommasoberlose/another-widget#233]
Hope another widget provide a option to set the event refresh frequency to 1 min like the clock.

**Comment by Moutony** [comment]
*Need

**Comment by devindang** [comment]
> *Need

damn gboard

**Comment by tommasoberlose** [comment]
Hey @devindang, I can't enable a one minute refresh because the application would be killed by the OS after a while.
I already awake the device very often to update the weather or to respond to the glance providers and that could not be affordable.

The clock is based on a different UI component that is updated by the system itself, that's why it can't be stylized.
